// Can be converted to JSON

var demoSampleURLs = [
  "assets/audio/Guitar_DI_Track.mp3",
  "assets/audio/LasseMagoDI.mp3",
  "assets/audio/RawPRRI.mp3",
  "assets/audio/Di-Guitar.mp3",
  "assets/audio/NarcosynthesisDI.mp3",
  "assets/audio/BlackSabbathNIB_rythmDI.mp3",
  "assets/audio/BlackSabbathNIBLead_DI.mp3",
  "assets/audio/BasketCase Greenday riff DI.mp3",
  "assets/audio/InBloomNirvanaRiff1DI.mp3",
  "assets/audio/Muse1Solo.mp3",
  "assets/audio/Muse2Rythm.mp3",
  "assets/audio/GuitarSolo1_DI.mp3",
  "assets/audio/GuitarSolo2_DI.mp3",
  "assets/audio/FolkAcousticDI.mp3",
  "assets/audio/3F_DI_guitar.wav",
  "assets/audio/DIGuitarRIFF.mp3",
  "assets/audio/CleanGuitarRiff.mp3",
  "assets/audio/Master-Of-Puppets.mp3",
  "assets/audio/Funky-Guitar.mp3",
  "assets/audio/AcousticRythmPalm.mp3",
  "assets/audio/AmericanVintages.mp3",
  "assets/audio/ArpegiosClean.mp3",
  "assets/audio/BoDiddleyLike.mp3",
  "assets/audio/BridgeCleanP90QuietCoil.mp3",
  "assets/audio/ClassicRockRiff.mp3",
  "assets/audio/CleanChords.mp3",
  "assets/audio/DryGuitarKemper.mp3",
  "assets/audio/GuitarRythm1.wav",
  "assets/audio/GuitarRythm2.wav",
  "assets/audio/HendrixLike.mp3",
  "assets/audio/HendrixLike2.mp3",
  "assets/audio/HendrixLike3.mp3",
  "assets/audio/HendrixLike4.mp3",
  "assets/audio/HendrixLike6.wav",
  "assets/audio/RIffMetalShort.wav",
  "assets/audio/RockRIff.mp3",
  "assets/audio/amp_dry_clean_jordan_metal.mp3"
];
